### ISSUE TITLE
where are the PhysioNet.info files that defined the scaling applied to the raw data file?

### ISSUE THREAD

**Issue by VBRay** [mathworks/physionet_ECG_data#1]
I cannot find the PhysioNet.info files that defined the scaling applied to the raw data file?

**Comment by wmking** [comment]
These are generated by PhysioBank ATM

https://www.physionet.org/cgi-bin/atm/ATM

For example:

1.) choose the MIT-BIH Arrythmia Database (mitdb) from the Database drop down.
2.) choose Record 100
3.) Select output to end
4.) Select time format samples
5.) Select data format standard
6.) In Toolbox, select "Export signals as .mat"

You should see under "Download these files" you have files 100m.mat, 100m.info, 100m.hea.

The .info files contain information like sampling frequency, gain and base values. Here is the sample .info file:

Source: record mitdb/100
val has 2 rows (signals) and 650000 columns (samples/signal)
Duration:    30:05
Sampling frequency: 360 Hz  Sampling interval: 0.002777777778 sec
Row	Signal	Gain	Base	Units
1	MLII	200	0	mV
2	V5	200	0	mV

To convert from raw units to the physical units shown
above, call the 'rdmat.m' function from the wfdb-matlab
toolbox: https://physionet.org/physiotools/matlab/wfdb-app-matlab/

We do not include all those files here because we have already resampled the data and applied the scaling for your for use in the example.

Hope that helps,
Wayne
